service: folk-coder

image: cbiperson/folk-coder

servers:
  web:
    - srv824516.hstgr.cloud

proxy:
  ssl: true
  host: folkcoder.com

registry:
  server: ghcr.io
  username: CbiPerson
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "folk_coder_storage:/rails/storage"

builder:
  arch: amd64
